import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'uk' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getTMDBLanguage: () => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'uk';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    if (!key) return '';
    if (!translations[language]) return key;
    return translations[language][key] || key;
  };

  // Функція для отримання мови у форматі TMDB (uk-UA або en-US)
  const getTMDBLanguage = (): string => {
    return language === 'uk' ? 'uk-UA' : 'en-US';
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getTMDBLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const translations: Record<Language, Record<string, string>> = {
  uk: {
    'nav.dashboard': 'Головна',
    'nav.movies': 'Фільми',
    'nav.anime': 'Аніме',
    'nav.series': 'Серіали',
    'nav.cartoons': 'Мультфільми',
    'nav.subscription': 'Підписка',
    'nav.terms': 'Умови',
    'user.profile': 'Профіль',
    'user.logout': 'Вийти',
    'user.settings': 'Налаштування',
    'user.subscriptions': 'Підписки',
    'user.premium': 'Преміум користувач',
    'user.exit_account': 'Вийти з акаунту',
    'language.ukrainian': 'Українська',
    'language.english': 'English',
    'auth.login': 'Вхід',
    'auth.register': 'Реєстрація',
    'auth.password_recovery': 'Відновлення пароля',
    'auth.new_password': 'Новий пароль',
    'auth.email_sent': 'Email відправлено',
    'auth.create_account': 'Створити новий акаунт',
    'auth.email_placeholder': 'example@gmail.com',
    'auth.password_placeholder': '••••••••',
    'auth.confirm_password_placeholder': 'Повторіть пароль',
    'auth.login_button': 'Увійти',
    'auth.logging_in': 'Вхід...',
    'auth.login_success': 'Вітаємо! Ви успішно увійшли в акаунт',
    'auth.register_button': 'Зареєструватися',
    'auth.registering': 'Реєстрація...',
    'auth.register_success': 'Реєстрація успішна! Тепер ви можете увійти в акаунт',
    'auth.already_have_account': 'Вже є акаунт?',
    'auth.email_taken': 'Цей email вже зайнятий',
    'validation.enter_dob': 'Вкажіть дату народження',
    'auth.agree_prefix': 'Я згоден з',
    'auth.terms': 'умовами використання',
    'auth.forgot_password': 'Забули пароль?',
    'auth.invalid_credentials': 'Невірний email або пароль',
    'auth.error_generic': 'Щось пішло не так. Спробуйте ще раз.',
    'validation.enter_name': 'Введіть ім\'я',
    'validation.enter_email': 'Введіть email',
    'validation.invalid_email': 'Невірний формат email',
    'validation.enter_password': 'Введіть пароль',
    'validation.password_min': 'Пароль має бути не менше 8 символів',
    'validation.passwords_mismatch': 'Паролі не співпадають',
    'validation.accept_terms': 'Потрібно прийняти умови',
    'subscription.title': 'Плани підписки',
    'admin.users': 'Користувачі',
    'dashboard.main': 'Головна',
    'dashboard.search': 'Пошук: Пуститися берега, Декстер, Наруто, Оппенгеймер...',
    'dashboard.find': 'Знайти',
    'dashboard.back': 'Повернутись до головної',
    'dashboard.search_results': 'Результати пошуку:',
    'dashboard.top_movies': 'Топ 20 популярних фільмів',
    'dashboard.top_series': 'Топ 20 популярних серіалів',
    'dashboard.loading': 'Завантажуємо контент...',
    'profile.title': 'Мій профіль',
    'profile.edit_profile': 'Редагувати профіль',
    'profile.change_avatar': 'Змінити аватар',
    'profile.name': 'Ім\'я',
    'profile.email': 'Email',
    'profile.save': 'Зберегти',
    'profile.cancel': 'Скасувати',
    'profile.upload_avatar': 'Завантажити аватар',
    'profile.loading': 'Завантаження профілю...',
    'profile.date_of_birth': 'Дата народження',
    'profile.update_failed': 'Не вдалося оновити профіль',
    'footer.copyright': '© 2025 Nexo Cinema. Всі права захищені.',
    'movies.welcome': 'Ласкаво просимо до Nexo Cinema!',
    'movies.top_100': 'Топ‑100 фільмів зараз',
    'movies.loading_error': 'Помилка завантаження топ‑100 фільмів. Перевірте інтернет або токен TMDB.',
    'movies.search_min_chars': 'Введіть хоча б 2 символи для пошуку.',
    'movies.search_error': 'Нічого не знайдено. Спробуйте іншу назву або частину назви.',
    'movies.connection_error': 'Помилка з\'єднання з TMDB. Перевірте токен і інтернет.',
    'series.welcome': 'Ласкаво просимо до Nexo Cinema!',
    'series.top_100': 'Топ‑100 серіалів зараз',
    'series.loading_error': 'Помилка завантаження топ серіалів. Перевірте токен або інтернет.',
    'series.search_min_chars': 'Введіть хоча б 2 символи.',
    'series.search_error': 'Серіали не знайдено. Спробуйте: Гра престолів, Пуститися берега, Друзі, ВандаВіжн, Чорне дзеркало...',
    'anime.welcome': 'Вітаємо у світі аніме!',
    'anime.top': 'Топ аніме (фільми та серіали)',
    'anime.loading': 'Завантажуємо топ аніме...',
    'anime.searching': 'Шукаємо аніме...',
    'cartoons.welcome': 'Вітаємо у світі мультфільмів!',
    'cartoons.top_100': 'Топ‑100 найкращих мультфільмів',
    'cartoons.loading': 'Завантажуємо топ мультфільмів...',
    'cartoons.searching': 'Шукаємо мультфільми...',
    'series.loading': 'Завантажуємо топ серіалів...',
    'series.searching': 'Шукаємо серіали...',
    'movies.loading': 'Завантажуємо топ фільмів...',
    'movies.searching': 'Шукаємо фільми...',
    'common.find_button': 'Знайти',
    'common.searching': 'Шукаємо...',
    'movies.search_placeholder': 'Шукати фільми: Ілюзія обману, Титанік, Гаррі Поттер, Оппенгеймер...',
    'series.search_placeholder': 'Шукати серіали: Гра престолів, Пуститися берега, Друзі, ВандаВіжн, Чорне дзеркало...',
    'anime.search_placeholder': 'Шукати аніме: Наруто, Ван Піс, Атака титанів, Токійський гуль, Твоє ім\'я...',
    'cartoons.search_placeholder': 'Шукати мультфільми: Король Лев, Холодне серце, Шрек, Вгору, Мадагаскар, Тачки...',
    'favorites.add': 'Додати до улюблених',
    'favorites.remove': 'Видалити з улюблених',
    'favorites.title': 'Улюблені',
    'favorites.empty': 'У вас немає улюблених',
    'favorites.added': 'Додано до улюблених',
    'favorites.removed': 'Видалено з улюблених',
    'watch_history.title': 'Історія переглядів',
    'watch_history.empty': 'Ви ще нічого не переглядали.',
    'watch_history.movie': 'Фільм',
    'watch_history.series': 'Серіал',
    'watch_history.cartoon': 'Мультфільм',
    'watch_history.clear': 'Очистити історію',
    'watch_history.remove': 'Видалити',
    'anime.loading_error': 'Помилка завантаження топ аніме. Перевірте токен або інтернет.',
    'anime.search_error': 'Аніме не знайдено. Спробуйте іншу назву (Наруто, Ван Піс, Атака титанів, Твоє ім\'я...).',
    'cartoons.loading_error': 'Помилка завантаження топ мультфільмів. Перевірте токен або інтернет.',
    'cartoons.search_error': 'Мультфільми не знайдені.',
    'common.search_min_chars': 'Введіть хоча б 2 символи.',
    'common.search_error_connection': 'Помилка пошуку. Перевірте інтернет або токен.',
    'common.load_more': 'Показати ще',
    'common.no_image': 'Немає зображення',
    'profile.welcome': 'Мій профіль',
    'profile.save_changes': 'Зберегти зміни',
    'profile.cancel_edit': 'Скасувати',
    'profile.select_image': 'Оберіть зображення',
    'profile.image_too_large': 'Зображення занадто велике (макс. 5 МБ)',
    'profile.image_selected': 'Фото обрано! Натисніть «Зберегти зміни»',
    'profile.not_authorized': 'Ви не авторизовані',
    'profile.read_error': 'Помилка читання даних',
    'profile.my_profile': 'Мій профіль',
    'profile.full_name': 'Ім\'я та прізвище',
    'profile.enter_name': 'Введіть ваше ім\'я',
    'profile.email_not_specified': 'Email не вказано',
    'profile.premium_user': 'Преміум користувач',
    'profile.cancel_btn': 'Скасувати',
    'profile.save_btn': 'Зберегти зміни',
    'profile.profile_updated': 'Профіль успішно оновлено!',
    'common.year': 'рік',
    'landing.tagline': 'Тисячі фільмів, серіалів, мультфільмів та аніме — українською, в один клік.',
    'landing.login': 'Увійти',
    'landing.register_free': 'Зареєструватися безкоштовно',
    'landing.features': 'Без реклами • Висока якість • Доступ з будь-якого пристрою',
    'landing.popular_movies': 'Популярні фільми зараз',
    'landing.top_series': 'Топ серіалів, які дивляться всі',
    'landing.loading': 'Завантажуємо найкращий контент для вас...',
    'landing.cta_title': 'Почни дивитися вже сьогодні',
    'landing.cta_description': 'Реєстрація займає 30 секунд. Доступ до всього каталогу — одразу після входу.',
    'landing.movie': 'Фільм',
    'landing.series': 'Серіал',
    'landing.login_required': 'Залогіньтесь, щоб переглядати деталі фільмів та серіалів!',
    'common.unknown': 'Невідомо',
    'common.user': 'Користувач',
    'common.poster_missing': 'Постер відсутній',
    'common.cartoon': 'Мультфільм',
    'common.series': 'Серіал',
    'common.anime_series': 'Аніме-серіал',
    'common.anime_movie': 'Аніме-фільм',
    'subscription.choose_plan': 'Оберіть свій план',
    'subscription.choose_plan_desc': 'Дивіться фільми, серіали, аніме та мультфільми без обмежень. Оберіть ідеальний план для себе чи всієї родини.',
    'subscription.basic': 'Базовий',
    'subscription.basic_free': 'Безкоштовно',
    'subscription.basic_with_ads': 'З рекламою',
    'subscription.basic_access': 'Доступ до тисяч фільмів',
    'subscription.basic_access_desc': 'Класика та хіти',
    'subscription.basic_recommendations': 'Персональні рекомендації',
    'subscription.basic_no_features': 'HD, без реклами, офлайн, 4K',
    'subscription.basic_continue': 'Продовжити з Базовим',
    'subscription.standard': 'Стандарт',
    'subscription.standard_price': 'грн/міс',
    'subscription.standard_features': 'Full HD + без реклами',
    'subscription.most_popular': 'Найпопулярніший',
    'subscription.standard_all_basic': 'Все з Базового',
    'subscription.standard_full_hd': 'Full HD 1080p',
    'subscription.standard_no_ads': 'Без реклами',
    'subscription.standard_offline': 'Офлайн завантаження',
    'subscription.standard_devices': 'До 2 пристроїв одночасно',
    'subscription.standard_parental': 'Батьківський контроль',
    'subscription.standard_subscribe': 'Оформити Стандарт',
    'subscription.premium': 'Преміум',
    'subscription.premium_features': '4K + вся родина',
    'subscription.premium_all_standard': 'Все зі Стандарту',
    'subscription.premium_4k': '4K Ultra HD + HDR',
    'subscription.premium_devices': 'До 4 пристроїв одночасно',
    'subscription.premium_exclusive': 'Ексклюзивні прем\'єри',
    'subscription.premium_subscribe': 'Оформити Преміум',
    'subscription.footer': 'Безпечна оплата через Google Pay • Скасувати можна будь-коли • Без зобов\'язань',
  },
  en: {
    'nav.dashboard': 'Main',
    'nav.movies': 'Movies',
    'nav.anime': 'Anime',
    'nav.series': 'Series',
    'nav.cartoons': 'Cartoons',
    'nav.subscription': 'Subscription',
    'nav.terms': 'Terms',
    'user.profile': 'Profile',
    'user.logout': 'Logout',
    'user.settings': 'Settings',
    'user.subscriptions': 'Subscriptions',
    'user.premium': 'Premium User',
    'user.exit_account': 'Exit Account',
    'language.ukrainian': 'Українська',
    'language.english': 'English',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.password_recovery': 'Password Recovery',
    'auth.new_password': 'New Password',
    'auth.confirm_password_placeholder': 'Repeat password',
    'auth.login_button': 'Login',
    'auth.logging_in': 'Logging in...',
    'auth.login_success': 'Welcome! You have successfully signed in',
    'auth.register_button': 'Register',
    'auth.registering': 'Registering...',
    'auth.create_account': 'Create a new account',
    'auth.email_placeholder': 'example@gmail.com',
    'auth.password_placeholder': '••••••••',
    'auth.register_success': 'Registration successful! You can now log in',
    'auth.already_have_account': 'Already have an account?',
    'auth.email_taken': 'This email is already taken',
    'validation.enter_dob': 'Please enter date of birth',
    'auth.agree_prefix': 'I agree to the',
    'auth.terms': 'terms of service',
    'auth.forgot_password': 'Forgot password?',
    'auth.invalid_credentials': 'Invalid email or password',
    'auth.error_generic': 'Something went wrong. Please try again.',
    'validation.enter_name': 'Enter name',
    'validation.enter_email': 'Enter email',
    'validation.invalid_email': 'Invalid email format',
    'validation.enter_password': 'Enter password',
    'validation.password_min': 'Password must be at least 8 characters',
    'validation.passwords_mismatch': 'Passwords do not match',
    'validation.accept_terms': 'You must accept the terms',
    'subscription.title': 'Subscription Plans',
    'admin.users': 'Users',
    'dashboard.main': 'Main',
    'dashboard.search': 'Search: Stranger Things, Dexter, Naruto, Oppenheimer...',
    'dashboard.find': 'Find',
    'dashboard.back': 'Back to main',
    'dashboard.search_results': 'Search results:',
    'dashboard.top_movies': 'Top 20 Popular Movies',
    'dashboard.top_series': 'Top 20 Popular Series',
    'dashboard.loading': 'Loading content...',
    'profile.title': 'My Profile',
    'profile.edit_profile': 'Edit Profile',
    'profile.change_avatar': 'Change Avatar',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.upload_avatar': 'Upload Avatar',
    'profile.loading': 'Loading profile...',
    'profile.date_of_birth': 'Date of birth',
    'profile.update_failed': 'Failed to update profile',
    'footer.copyright': '© 2025 Nexo Cinema. All rights reserved.',
    'movies.welcome': 'Welcome to Nexo Cinema!',
    'movies.top_100': 'Top 100 Movies Now',
    'movies.loading_error': 'Error loading top 100 movies. Check internet or TMDB token.',
    'movies.search_min_chars': 'Enter at least 2 characters to search.',
    'movies.search_error': 'Nothing found. Try another title or part of the title.',
    'movies.connection_error': 'Connection error with TMDB. Check token and internet.',
    'series.welcome': 'Welcome to Nexo Cinema!',
    'series.top_100': 'Top 100 Series Now',
    'series.loading_error': 'Error loading top series. Check token or internet.',
    'series.search_min_chars': 'Enter at least 2 characters.',
    'series.search_error': 'Series not found. Try: Game of Thrones, Breaking Bad, Friends, WandaVision, Black Mirror...',
    'anime.welcome': 'Welcome to the world of anime!',
    'anime.top': 'Top Anime (movies and series)',
    'anime.loading': 'Loading top anime...',
    'anime.searching': 'Searching for anime...',
    'cartoons.welcome': 'Welcome to the world of cartoons!',
    'cartoons.top_100': 'Top 100 Best Cartoons',
    'cartoons.loading': 'Loading top cartoons...',
    'cartoons.searching': 'Searching for cartoons...',
    'series.loading': 'Loading top series...',
    'series.searching': 'Searching for series...',
    'movies.loading': 'Loading top movies...',
    'movies.searching': 'Searching for movies...',
    'common.find_button': 'Find',
    'common.searching': 'Searching...',
    'movies.search_placeholder': 'Search movies: The Illusionist, Titanic, Harry Potter, Oppenheimer...',
    'series.search_placeholder': 'Search series: Game of Thrones, Breaking Bad, Friends, WandaVision, Black Mirror...',
    'anime.search_placeholder': 'Search anime: Naruto, One Piece, Attack on Titan, Tokyo Ghoul, Your Name...',
    'cartoons.search_placeholder': 'Search cartoons: The Lion King, Frozen, Shrek, Up, Madagascar, Cars...',
    'favorites.add': 'Add to Favorites',
    'favorites.remove': 'Remove from Favorites',
    'favorites.title': 'My Favorites',
    'favorites.empty': 'You have no favorites',
    'favorites.added': 'Added to Favorites',
    'favorites.removed': 'Removed from Favorites',
    'watch_history.title': 'Watch History',
    'watch_history.empty': 'You have not watched anything yet.',
    'watch_history.movie': 'Movie',
    'watch_history.series': 'Series',
    'watch_history.cartoon': 'Cartoon',
    'watch_history.clear': 'Clear History',
    'watch_history.remove': 'Remove',
    'anime.loading_error': 'Error loading top anime. Check token or internet.',
    'anime.search_error': 'Anime not found. Try another title (Naruto, One Piece, Attack on Titan, Your Name...).',
    'cartoons.loading_error': 'Error loading top cartoons. Check token or internet.',
    'cartoons.search_error': 'Cartoons not found.',
    'common.search_min_chars': 'Enter at least 2 characters.',
    'common.search_error_connection': 'Search error. Check internet or token.',
    'common.load_more': 'Load More',
    'common.no_image': 'No image',
    'profile.welcome': 'My Profile',
    'profile.save_changes': 'Save Changes',
    'profile.cancel_edit': 'Cancel',
    'profile.select_image': 'Select Image',
    'profile.image_too_large': 'Image is too large (max. 5 MB)',
    'profile.image_selected': 'Photo selected! Click "Save Changes"',
    'profile.not_authorized': 'You are not authorized',
    'profile.read_error': 'Error reading data',
    'profile.my_profile': 'My Profile',
    'profile.full_name': 'Full Name',
    'profile.enter_name': 'Enter your name',
    'profile.email_not_specified': 'Email not specified',
    'profile.premium_user': 'Premium User',
    'profile.cancel_btn': 'Cancel',
    'profile.save_btn': 'Save Changes',
    'profile.profile_updated': 'Profile updated successfully!',
    'common.year': 'year',
    'landing.tagline': 'Thousands of movies, series, cartoons and anime — in Ukrainian, in one click.',
    'landing.login': 'Login',
    'landing.register_free': 'Sign up for free',
    'landing.features': 'Ad-free • High quality • Access from any device',
    'landing.popular_movies': 'Popular Movies Now',
    'landing.top_series': 'Top Series Everyone is Watching',
    'landing.loading': 'Loading the best content for you...',
    'landing.cta_title': 'Start Watching Today',
    'landing.cta_description': 'Registration takes 30 seconds. Access to the entire catalog — immediately after login.',
    'landing.movie': 'Movie',
    'landing.series': 'Series',
    'landing.login_required': 'Please log in to view movie and series details!',
    'common.unknown': 'Unknown',
    'common.user': 'User',
    'common.poster_missing': 'Poster missing',
    'common.cartoon': 'Cartoon',
    'common.series': 'Series',
    'common.anime_series': 'Anime Series',
    'common.anime_movie': 'Anime Movie',
    'subscription.choose_plan': 'Choose Your Plan',
    'subscription.choose_plan_desc': 'Watch movies, series, anime and cartoons without limits. Choose the perfect plan for you or your whole family.',
    'subscription.basic': 'Basic',
    'subscription.basic_free': 'Free',
    'subscription.basic_with_ads': 'With ads',
    'subscription.basic_access': 'Access to thousands of movies',
    'subscription.basic_access_desc': 'Classics and hits',
    'subscription.basic_recommendations': 'Personal recommendations',
    'subscription.basic_no_features': 'HD, ad-free, offline, 4K',
    'subscription.basic_continue': 'Continue with Basic',
    'subscription.standard': 'Standard',
    'subscription.standard_price': 'UAH/month',
    'subscription.standard_features': 'Full HD + ad-free',
    'subscription.most_popular': 'Most Popular',
    'subscription.standard_all_basic': 'Everything from Basic',
    'subscription.standard_full_hd': 'Full HD 1080p',
    'subscription.standard_no_ads': 'Ad-free',
    'subscription.standard_offline': 'Offline downloads',
    'subscription.standard_devices': 'Up to 2 devices simultaneously',
    'subscription.standard_parental': 'Parental controls',
    'subscription.standard_subscribe': 'Subscribe to Standard',
    'subscription.premium': 'Premium',
    'subscription.premium_features': '4K + whole family',
    'subscription.premium_all_standard': 'Everything from Standard',
    'subscription.premium_4k': '4K Ultra HD + HDR',
    'subscription.premium_devices': 'Up to 4 devices simultaneously',
    'subscription.premium_exclusive': 'Exclusive premieres',
    'subscription.premium_subscribe': 'Subscribe to Premium',
    'subscription.footer': 'Secure payment via Google Pay • Cancel anytime • No commitments',
  },
};
